### ISSUE TITLE
fix: show validation only when the user has typed something

### ISSUE THREAD

**Issue by AyanavaKarmakar** [TypeSafe-Travellers/trippins#103]
- this condition will rename the same (for the button on click validation)
![image](https://user-images.githubusercontent.com/89210438/214941382-2e269944-9cf0-464e-8bb0-95fa27fb3cc5.png)

- update this so that warning only shows when the length is more than 1

for example -

```ts
length !== 0 && length < 3
```

![image](https://user-images.githubusercontent.com/89210438/214941662-06cc816f-127a-41f1-9769-996fb1642beb.png)

- do this for all validations

**Comment by ssarkar551** [comment]
![image](https://user-images.githubusercontent.com/46297022/215345057-046b32ca-8eac-42b8-a4c0-e70ced6d7c2e.png)
